### ISSUE TITLE
Maven dependency

### ISSUE THREAD

**Issue by JuanitaSmith** [vitorsvieira/scala-iso#2]
I'm adding the following as maven dependency
        <dependency>
            <groupId>com.vitorsvieira</groupId>
            <artifactId>scala-iso</artifactId>
            <version>0.1.2</version>
        </dependency>

however I get message that dependency is not found. How should I configure Maven ?

**Comment by vitorsvieira** [comment]
You can add the following:

```
<dependency>
    <groupId>com.vitorsvieira</groupId>
    <artifactId>scala-iso_2.12</artifactId>
    <version>0.1.2</version>
</dependency>
```
